"""Finds the face in every Transfermarkt and Wikimedia player photo, so avatars can zoom in on it.

Premier League photos are consistent head-and-shoulders cut-outs and are left alone. The other sources vary (half-length
portraits, action shots, group photos), so each image is downloaded once and run through OpenCV's face detector.
The biggest face gives a focal point and size, written to data/faces.js as
    window.GM_FACES = {"tm:<portrait id>": [cx, cy, w], "w:<name>|<first season>": [cx, cy, w]}
with cx, cy the face centre and w its width, all as percentages of the image. Images with no clear face are recorded
as [tag] so they aren't fetched again (the tag is a fingerprint of the picture, see main). Usage: python tools/face_points.py [max images]   (needs opencv-python-headless<5: OpenCV 5 dropped the Haar cascades)
"""
import hashlib, json, os, re, sys, time, urllib.request
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
DATA, ALL, PHOTOS, OUT = ROOT / 'data/players.js', ROOT / 'data/players_all.js', ROOT / 'data/photos.js', ROOT / 'data/faces.js'
UA = 'GoalMachinePhotos/1.0 (https://opportunisticgames.github.io/goal-machine/; fan-made quiz game)'
TM = 'https://img.a.transfermarkt.technology/portrait/header/{}.jpg'
def cascade(name):
    return cv2.CascadeClassifier(cv2.data.haarcascades + name)


CASCADE = cascade('haarcascade_frontalface_default.xml')
FRONTAL = [CASCADE, cascade('haarcascade_frontalface_alt2.xml'), cascade('haarcascade_frontalface_alt.xml')]
PROFILE = cascade('haarcascade_profileface.xml')
# OpenCV's YuNet, a small neural face detector: far better than the Haar cascades at faces that are small, turned or
# in shadow (action shots, crowds). The workflow downloads the model next to this file; without it, Haar only.
YUNET = Path(os.environ.get('YUNET', Path(__file__).with_name('face_detection_yunet.onnx')))
DETECTOR = 3  # raise when face finding gets better: every photo is looked at again


def yunet(img):
    """Faces as (x, y, w, h, score), found by YuNet on the picture (small pictures are scaled up first)."""
    if not YUNET.exists():
        return []
    h, w = img.shape[:2]
    k = max(1.0, 480 / min(w, h))
    if k > 1:
        img = cv2.resize(img, (int(w * k), int(h * k)), interpolation=cv2.INTER_CUBIC)
    det = cv2.FaceDetectorYN.create(str(YUNET), '', (img.shape[1], img.shape[0]), 0.7, 0.3, 50)
    _, faces = det.detect(img)
    return [(f[0] / k, f[1] / k, f[2] / k, f[3] / k, float(f[-1])) for f in (faces if faces is not None else [])]


def load_js(path):
    s = path.read_text()
    return json.loads(s[s.index('=') + 1:s.rindex(';')])


def fetch(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA, 'Referer': ''})
    for i in range(3):
        try:
            with urllib.request.urlopen(req, timeout=20) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            if e.code in (403, 404, 410):
                return None
        except Exception:
            pass
        time.sleep(1 + 2 * i)
    return None


def face(data):
    img = cv2.imdecode(np.frombuffer(data, np.uint8), cv2.IMREAD_COLOR)
    if img is None:
        return []
    h, w = img.shape[:2]
    # YuNet first: the subject is the best mix of big, sure and high in the picture (a crowd face is small, a
    # team-mate's is usually lower down or off to the side)
    nn = yunet(img)
    if nn:
        x, y, fw, fh, _ = max(nn, key=lambda f: f[4] * f[2] * f[3] * (1.25 - 0.5 * (f[1] + f[3] / 2) / h))
        return [round(float(100 * (x + fw / 2) / w), 1), round(float(100 * (y + fh / 2) / h), 1), round(float(100 * fw / w), 1)]
    grey = cv2.equalizeHist(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY))
    min_side = max(20, int(min(w, h) * 0.08))
    size = (min_side, min_side)
    found, mirrored = [], False
    # the detectors in turn, strictest first: front-on (three trained versions), a left-facing profile, then a right-facing
    # one (the picture flipped), and last the first detector again with fewer neighbours required
    for det, neighbours in [(FRONTAL[0], 5), (FRONTAL[1], 4), (FRONTAL[2], 4), (PROFILE, 4)]:
        found = list(det.detectMultiScale(grey, 1.1, neighbours, minSize=size))
        if found:
            break
    if not found:
        found = list(PROFILE.detectMultiScale(cv2.flip(grey, 1), 1.1, 4, minSize=size))
        mirrored = bool(found)
    if not found:
        found = list(CASCADE.detectMultiScale(grey, 1.05, 3, minSize=(max(30, int(min(w, h) * 0.12)),) * 2))
    if not found:
        return []
    x, y, fw, fh = max(found, key=lambda f: f[2] * f[3])  # the biggest face is the subject
    cx = 100 * (x + fw / 2) / w
    return [round(float(100 - cx if mirrored else cx), 1), round(float(100 * (y + fh / 2) / h), 1), round(float(100 * fw / w), 1)]


def save(faces):
    OUT.write_text('// Generated by tools/face_points.py - where the face is in each non-PL player photo\n'
                   'window.GM_FACES=' + json.dumps(dict(sorted(faces.items())), separators=(',', ':')) + ';\n')


def main():
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else 10 ** 9
    d = load_js(DATA)
    photos = load_js(PHOTOS) if PHOTOS.exists() else {}
    faces = load_js(OUT) if OUT.exists() else {}
    # a better detector looks at every photo again, a few thousand a run, but keeps the old faces until it gets to them
    # (wiping them first left thousands of avatars without a face between runs)
    faces['_detector'] = DETECTOR
    jobs = []
    # every-player file too (Extreme / Purist), for its Transfermarkt portraits
    rows = d['players'] + (load_js(ALL)['players'] if ALL.exists() else [])
    for r in rows:
        if len(r) > 12 and r[12] and ('tm:' + r[12], TM.format(r[12])) not in jobs:
            jobs.append(('tm:' + r[12], TM.format(r[12])))
        ph = photos.get(f'{r[0]}|{r[6]}')
        if ph and ph.get('w'):
            jobs.append((f'w:{r[0]}|{r[6]}', ph['w']))
    # each entry ends with a short fingerprint of the picture it was found in, so a player whose photo changes is
    # looked at again ([cx, cy, w, tag], or [tag] when there's no clear face)
    # (the tag also carries the detector's number, so an entry from an older detector is looked at again)
    tag = lambda url: hashlib.md5(url.encode()).hexdigest()[:6] + str(DETECTOR)
    fresh = [j for j in jobs if j[0] not in faces]  # never looked at: first
    stale = [j for j in jobs if j[0] in faces and (faces[j[0]] or [''])[-1] != tag(j[1])]
    todo = (fresh + stale)[:limit]
    print(f"{len(fresh)} never looked at, {len(stale)} from an older detector", file=sys.stderr)
    print(f'{len(jobs)} photos, {len(todo)} to check', file=sys.stderr)
    hit = 0
    for n, (k, url) in enumerate(todo):
        # a bigger copy of a Wikimedia thumbnail, so small faces in action shots can be found (positions are percentages)
        data = fetch(re.sub(r'/(\d+)px-', '/640px-', url)) if '/thumb/' in url else None
        data = data or fetch(url)
        if data is None:
            continue  # try again next run
        faces[k] = face(data) + [tag(url)]
        hit += len(faces[k]) > 1
        if n % 100 == 0:
            print(f'  {n}/{len(todo)} faces found {hit}', file=sys.stderr)
        if n % 300 == 299:
            save(faces)  # a long run that hits the job's time limit keeps what it found
        time.sleep(0.05)
    save(faces)
    print(f'faces found {hit} of {len(todo)} checked; {len(faces)} recorded', file=sys.stderr)


if __name__ == '__main__':
    main()
