"""Finds the face in every Transfermarkt and Wikimedia player photo, so avatars can zoom in on it.

Premier League photos are consistent head-and-shoulders cut-outs and are left alone. The other sources vary (half-length
portraits, action shots, group photos), so each image is downloaded once and run through OpenCV's face detector.
The biggest face gives a focal point and size, written to data/faces.js as
    window.GM_FACES = {"tm:<portrait id>": [cx, cy, w], "w:<name>|<first season>": [cx, cy, w]}
with cx, cy the face centre and w its width, all as percentages of the image. Images with no clear face are recorded
as [] so they aren't fetched again. Usage: python tools/face_points.py [max images]   (needs opencv-python-headless<5: OpenCV 5 dropped the Haar cascades)
"""
import json, re, sys, time, urllib.request
from pathlib import Path

import cv2
import numpy as np

ROOT = Path(__file__).resolve().parent.parent
DATA, ALL, PHOTOS, OUT = ROOT / 'data/players.js', ROOT / 'data/players_all.js', ROOT / 'data/photos.js', ROOT / 'data/faces.js'
UA = 'GoalMachinePhotos/1.0 (https://opportunisticgames.github.io/goal-machine/; fan-made quiz game)'
TM = 'https://img.a.transfermarkt.technology/portrait/header/{}.jpg'
def cascade(name):
    return cv2.CascadeClassifier(cv2.data.haarcascades + name)


CASCADE = cascade('haarcascade_frontalface_default.xml')
FRONTAL = [CASCADE, cascade('haarcascade_frontalface_alt2.xml'), cascade('haarcascade_frontalface_alt.xml')]
PROFILE = cascade('haarcascade_profileface.xml')


def load_js(path):
    s = path.read_text()
    return json.loads(s[s.index('=') + 1:s.rindex(';')])


def fetch(url):
    req = urllib.request.Request(url, headers={'User-Agent': UA, 'Referer': ''})
    for i in range(3):
        try:
            with urllib.request.urlopen(req, timeout=20) as r:
                return r.read()
        except urllib.error.HTTPError as e:
            if e.code in (403, 404, 410):
                return None
        except Exception:
            pass
        time.sleep(1 + 2 * i)
    return None


def face(data):
    img = cv2.imdecode(np.frombuffer(data, np.uint8), cv2.IMREAD_COLOR)
    if img is None:
        return []
    h, w = img.shape[:2]
    grey = cv2.equalizeHist(cv2.cvtColor(img, cv2.COLOR_BGR2GRAY))
    min_side = max(20, int(min(w, h) * 0.08))
    size = (min_side, min_side)
    found, mirrored = [], False
    # the detectors in turn, strictest first: front-on (three trained versions), a left-facing profile, then a right-facing
    # one (the picture flipped), and last the first detector again with fewer neighbours required
    for det, neighbours in [(FRONTAL[0], 5), (FRONTAL[1], 4), (FRONTAL[2], 4), (PROFILE, 4)]:
        found = list(det.detectMultiScale(grey, 1.1, neighbours, minSize=size))
        if found:
            break
    if not found:
        found = list(PROFILE.detectMultiScale(cv2.flip(grey, 1), 1.1, 4, minSize=size))
        mirrored = bool(found)
    if not found:
        found = list(CASCADE.detectMultiScale(grey, 1.05, 3, minSize=(max(30, int(min(w, h) * 0.12)),) * 2))
    if not found:
        return []
    x, y, fw, fh = max(found, key=lambda f: f[2] * f[3])  # the biggest face is the subject
    cx = 100 * (x + fw / 2) / w
    return [round(float(100 - cx if mirrored else cx), 1), round(float(100 * (y + fh / 2) / h), 1), round(float(100 * fw / w), 1)]


def main():
    limit = int(sys.argv[1]) if len(sys.argv) > 1 else 10 ** 9
    d = load_js(DATA)
    photos = load_js(PHOTOS) if PHOTOS.exists() else {}
    faces = load_js(OUT) if OUT.exists() else {}
    if faces.get('_detector') != 2:  # a better detector: faces it missed before are tried again
        faces = {k: v for k, v in faces.items() if v}
        faces['_detector'] = 2
    jobs = []
    # every-player file too (Extreme / Purist), for its Transfermarkt portraits
    rows = d['players'] + (load_js(ALL)['players'] if ALL.exists() else [])
    for r in rows:
        if len(r) > 12 and r[12] and ('tm:' + r[12], TM.format(r[12])) not in jobs:
            jobs.append(('tm:' + r[12], TM.format(r[12])))
        ph = photos.get(f'{r[0]}|{r[6]}')
        if ph and ph.get('w'):
            jobs.append((f'w:{r[0]}|{r[6]}', ph['w']))
    todo = [j for j in jobs if j[0] not in faces][:limit]
    print(f'{len(jobs)} photos, {len(todo)} to check', file=sys.stderr)
    hit = 0
    for n, (k, url) in enumerate(todo):
        data = fetch(url)
        if data is None:
            continue  # try again next run
        faces[k] = face(data)
        hit += bool(faces[k])
        if n % 100 == 0:
            print(f'  {n}/{len(todo)} faces found {hit}', file=sys.stderr)
        time.sleep(0.05)
    OUT.write_text('// Generated by tools/face_points.py - where the face is in each non-PL player photo\n'
                   'window.GM_FACES=' + json.dumps(dict(sorted(faces.items())), separators=(',', ':')) + ';\n')
    print(f'faces found {hit} of {len(todo)} checked; {len(faces)} recorded', file=sys.stderr)


if __name__ == '__main__':
    main()
